export {BG_NOTCHED} from './bgNotched';
export {PATTERN_DOTS} from './patternDots';
export {MASCOT} from './mascot';
export {ATMOSPHERE} from './atmosphere';
export {GOOGLE_LOGO} from './googleLogo';
export {APPLE_LOGO} from './appleLogo';
export {WHATSAPP_MARK} from './whatsAppMark';
export {COIN} from './coin';
export {DIRHAM} from './dirham';
